using System.Globalization;
using System.Text;

namespace Everywhere.ProcessIsolation.SourceGenerator;

internal static class RpcSourceEmitter
{
    public static string Generate(RpcContractModel contract)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        if (!string.IsNullOrEmpty(contract.NamespaceName))
        {
            builder.Append("namespace ").Append(contract.NamespaceName).AppendLine(";");
            builder.AppendLine();
        }

        AppendOperations(builder, contract);
        builder.AppendLine();
        AppendClient(builder, contract);
        builder.AppendLine();
        AppendBinding(builder, contract);
        return builder.ToString();
    }

    private static void AppendOperations(StringBuilder builder, RpcContractModel contract)
    {
        builder.Append("file static class ").Append(contract.Stem).AppendLine("RpcOperations");
        builder.AppendLine("{");
        foreach (var method in contract.Methods.OrderBy(static method => method.MethodId))
        {
            var operationId = ((uint)contract.ContractId << 16) | method.MethodId;
            builder.Append("    public const uint ").Append(method.OperationName).Append(" = 0x").Append(operationId.ToString("X8", CultureInfo.InvariantCulture)).AppendLine("u;");
        }

        builder.AppendLine("}");
    }

    private static void AppendClient(StringBuilder builder, RpcContractModel contract)
    {
        builder.Append(contract.Accessibility).Append(" sealed class ").Append(contract.Stem).Append("RpcClient(global::Everywhere.ProcessIsolation.Rpc.RpcConnection connection) : ").AppendLine(contract.InterfaceType);
        builder.Append("{");

        foreach (var method in contract.Methods)
        {
            builder.AppendLine();
            builder.AppendLine("    /// <inheritdoc />");
            builder.Append("    public ").Append(method.ReturnType).Append(' ').Append(method.EscapedName).Append('(').Append(method.RequestType).Append(' ').Append(method.RequestParameterName);
            if (method.CancellationTokenParameterName is not null)
            {
                builder.Append(", global::System.Threading.CancellationToken ").Append(method.CancellationTokenParameterName).Append(" = default");
            }

            builder.AppendLine(") =>");
            AppendClientInvocation(builder, contract, method);
        }

        builder.AppendLine("}");
    }

    private static void AppendClientInvocation(StringBuilder builder, RpcContractModel contract, RpcMethodModel method)
    {
        var cancellationToken = method.CancellationTokenParameterName ?? "default";
        builder.Append("        connection.");
        switch (method.Kind)
        {
            case RpcMethodKind.Response:
                builder.Append("InvokeAsync<").Append(method.RequestType).Append(", ").Append(method.ResultType).AppendLine(">(");
                break;
            case RpcMethodKind.Notification:
                builder.Append("SendNotificationAsync<").Append(method.RequestType).AppendLine(">(");
                break;
            case RpcMethodKind.Stream:
                builder.Append("InvokeStreamAsync<").Append(method.RequestType).Append(", ").Append(method.ResultType).AppendLine(">(");
                break;
        }

        builder.Append("            ").Append(contract.Stem).Append("RpcOperations.").Append(method.OperationName).AppendLine(",");
        builder.Append("            ").Append(method.RequestParameterName).AppendLine(",");
        builder.Append("            ").Append(cancellationToken).Append(')');
        if (method.ReturnsTask)
        {
            builder.Append(".AsTask()");
        }

        builder.AppendLine(";");
    }

    private static void AppendBinding(StringBuilder builder, RpcContractModel contract)
    {
        builder.Append(contract.Accessibility).Append(" static class ").Append(contract.Stem).AppendLine("RpcBinding");
        builder.AppendLine("{");
        builder.Append("    public static void Bind(global::Everywhere.ProcessIsolation.Rpc.RpcConnection connection, ").Append(contract.InterfaceType).AppendLine(" implementation)");
        builder.AppendLine("    {");
        foreach (var method in contract.Methods)
        {
            AppendBindingRegistration(builder, contract, method);
        }

        builder.AppendLine("    }");
        builder.AppendLine("}");
    }

    private static void AppendBindingRegistration(StringBuilder builder, RpcContractModel contract, RpcMethodModel method)
    {
        builder.Append("        connection.");
        switch (method.Kind)
        {
            case RpcMethodKind.Response:
                builder.Append("RegisterRequestHandler<").Append(method.RequestType).Append(", ").Append(method.ResultType).AppendLine(">(");
                break;
            case RpcMethodKind.Notification:
                builder.Append("RegisterNotificationHandler<").Append(method.RequestType).AppendLine(">(");
                break;
            case RpcMethodKind.Stream:
                builder.Append("RegisterStreamHandler<").Append(method.RequestType).Append(", ").Append(method.ResultType).AppendLine(">(");
                break;
        }

        builder.Append("            ").Append(contract.Stem).Append("RpcOperations.").Append(method.OperationName).AppendLine(",");
        builder.Append("            ");
        if (method is { ReturnsTask: false, CancellationTokenParameterName: not null })
        {
            builder.Append("implementation.").Append(method.EscapedName).AppendLine(");");
            return;
        }

        builder.Append("(request, cancellationToken) => ");
        if (method.ReturnsTask)
        {
            builder.Append("new global::System.Threading.Tasks.ValueTask");
            if (method.Kind == RpcMethodKind.Response)
            {
                builder.Append('<').Append(method.ResultType).Append('>');
            }

            builder.Append('(');
        }

        builder.Append("implementation.").Append(method.EscapedName).Append("(request");
        if (method.CancellationTokenParameterName is not null)
        {
            builder.Append(", cancellationToken");
        }

        builder.Append(')');
        if (method.ReturnsTask)
        {
            builder.Append(')');
        }

        builder.AppendLine(");");
    }
}