<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(TargetFrameworkPrefix)-macos</TargetFramework>
    <TargetPlatformVersion>26.2</TargetPlatformVersion>
    <SupportedOSPlatformVersion>12.0</SupportedOSPlatformVersion>
    <ApplicationId>com.sylinko.everywhere.automation-tests</ApplicationId>
    <RuntimeIdentifier>osx-arm64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <LinkMode>None</LinkMode>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Everywhere.Mac\Everywhere.Mac.csproj" />
  </ItemGroup>
</Project>
