<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>Everywhere.VisualContext.Avalonia.TestApp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.VisualContext.TestApp.Shared\Everywhere.VisualContext.TestApp.Shared.csproj" />
    <ProjectReference Include="..\Everywhere.VisualContext.Testing\Everywhere.VisualContext.Testing.csproj" />
  </ItemGroup>
</Project>
