<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.NET.Test.Sdk"/>
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="NUnit"/>
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter"/>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Everywhere.Automation\Everywhere.Automation.csproj" />
    <ProjectReference Include="..\..\src\Everywhere.Core\Everywhere.Core.csproj" />
    <ProjectReference Include="..\Everywhere.Automation.TestApp.Shared\Everywhere.Automation.TestApp.Shared.csproj" />
    <ProjectReference Include="..\Everywhere.Automation.Testing\Everywhere.Automation.Testing.csproj" />
  </ItemGroup>

</Project>
