<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <ApplicationManifest Condition="'$(IsWindows)' == 'true'">app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia.Controls.WebView" />
    <PackageReference Include="Avalonia.Desktop" />
    <PackageReference Include="Avalonia.Themes.Simple" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.Automation.TestApp.Shared\Everywhere.Automation.TestApp.Shared.csproj" />
  </ItemGroup>

  <Import Project="..\Everywhere.Automation.TestApp.Shared\AutomationTestApp.targets" />
</Project>
