<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>$(TargetFrameworkPrefix)-windows</TargetFramework>
    <RootNamespace>Everywhere.VisualContext.WinForms.TestApp</RootNamespace>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Everywhere.VisualContext.TestApp.Shared\Everywhere.VisualContext.TestApp.Shared.csproj" />
    <ProjectReference Include="..\Everywhere.VisualContext.Testing\Everywhere.VisualContext.Testing.csproj" />
  </ItemGroup>
</Project>
